export interface RecipeState {
    american: boolean,
    chinese: boolean,
    japanese: boolean,
    indian: boolean,
    greek: boolean,
    mexican: boolean,
    italian: boolean,
    thai: boolean,
    vietnamese: boolean,
    korean: boolean,

    vegan: boolean,
    vegetarian: boolean,
    pescatarian: boolean,
    kosher: boolean,
    halal: boolean,
    dairyFree: boolean,
    glutenFree: boolean,
    treeNuts: boolean,
    nutFree: boolean,
    shellfishFree: boolean,
    eggFree: boolean,
    soyFree: boolean,

    cost: string | undefined,
    time: string | undefined,
    skill: string | undefined,

    oven: boolean,
    microwave: boolean,
    airFryer: boolean,
    stove: boolean,
    BBQ: boolean,
    slowCooker: boolean,
    blender: boolean,
    pressureCooker: boolean,

    lowCal: boolean,
    highProtein: boolean,
    highFiber: boolean,
    lowSodium: boolean,
    lowSugar: boolean,
    redMeatFree: boolean,
    kidneyFriendly: boolean,
    lowCarb: boolean,
    alcoholFree: boolean,
    oilFree: boolean,
    carnivore: boolean,
    paleo: boolean,
    keto: boolean,
}

export const useCreateRecipeStore = defineStore("createRecipeStore", {
    state: (): RecipeState => ({
        american: false,
        chinese: false,
        japanese: false,
        indian: false,
        greek: false,
        mexican: false,
        italian: false,
        thai: false,
        vietnamese: false,
        korean: false,

        vegan: false,
        vegetarian: false,
        pescatarian: false,
        kosher: false,
        halal: false,
        dairyFree: false,
        glutenFree: false,
        treeNuts: false,
        nutFree: false,
        shellfishFree: false,
        eggFree: false,
        soyFree: false,

        cost: undefined,
        time: undefined,
        skill: undefined,

        oven: true,
        microwave: true,
        airFryer: true,
        stove: true,
        BBQ: true,
        slowCooker: true,
        blender: true,
        pressureCooker: true,

        lowCal: false,
        highProtein: false,
        highFiber: false,
        lowSodium: false,
        lowSugar: false,
        redMeatFree: false,
        kidneyFriendly: false,
        lowCarb: false,
        alcoholFree: false,
        oilFree: false,
        carnivore: false,
        paleo: false,
        keto: false,
    }),
    persist: {
        storage: persistedState.localStorage,
    },
});